name: Accessibility Tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  accessibility:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Start app
        run: npm run dev &

      - name: Wait for app to start
        run: npx wait-on http://localhost:5173

      - name: Make temp pa11y-ci config
        run: |
          echo '{"urls": ["http://localhost:5173/"]}' > .pa11yci.json

      - name: Run accessibility tests
        env:
          # Path to chrome on GitHub action runners
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome
        # Note that this will just test a version of the GUI with no
        # data in
        run: npx pa11y-ci
