name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
      - name: Display node and npm versions
        run: |
          node -v
          npm -v

      - name: Run a clean install of the project
        run: npm ci

      - name: Build the project
        run: |
          npm run build --if-present

      - name: Publish the package to npm
        run: npm publish --provenance --access public
